server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: CATDOGSHELTER-GATEWAY
  cloud:
    gateway:
      routes:
        # POST API 라우팅
        - id: CatDogShelter-post-service
          uri: lb://CATDOGSHELTER-POST-SERVICE
          predicates:
            - Path=/post-service/**
          filters:
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter # 테스트 할때 얘를 주석하고 테스트
        # User API 라우팅
        - id: CatDogShelter-user-api
          uri: lb://CATDOGSHELTER-USER-SERVICE
          predicates:
            - Path=/user-service/user/**
          filters:
            - RewritePath=/user-service/user/(?<segment>.*), /user/$\{segment}

        # ShelterHead API 라우팅
        - id: CatDogShelter-shelter-head-api
          uri: lb://CATDOGSHELTER-USER-SERVICE
          predicates:
            - Path=/user-service/shelter-head/**
          filters:
            - RewritePath=/user-service/shelter-head/(?<segment>.*), /shelter-head/$\{segment}
token:
  expiration_time: 43200000
  secret: "VKKCjFzrzJQE8oM69GmgavfauYLnHnQeG4k1ab/lrYtrEQMk7o0/3j8KmqM33prEOWs5IdSVhQsbKiV3UzFhHQ=="
